### ISSUE TITLE
Browser tab title says default "React App" and not "Pomodorset"

### ISSUE THREAD

**Issue by Balaguru4580** [Balaguru4580/pomodorset#1]
The title for the browser tab still shows the default react app title. Please change it to the name of the app, Pomodorset.

**Comment by DireWolf707** [comment]
Hye, I am new to open source and want to contribute to this issue for hacktoberfest.
Can you assign me this issue?

**Comment by Balaguru4580** [comment]
I'd suggest starting from October 1st so that your PR would be counted for Hacktoberfest. I appreciate you helping me out here!

**Comment by HunainHumail** [comment]
@Balaguru4580  Can you please assign this issue to me. I would love to work on this.

Thanks

**Comment by DireWolf707** [comment]
I already issued a PR @HunainHumail :)
