### ISSUE TITLE
Pressing Enter should start the timer.

### ISSUE THREAD

**Issue by Balaguru4580** [Balaguru4580/pomodorset#7]
Currently, we have to press the Start Timer button to start the timer via mouse.

It would be better if we could press enter instead, since we're already typing the values.

This could probably be achieved by handling the `onKeyPress` event in React whenever a keyboard key is pressed!

**Comment by ashutosh7i** [comment]
can i do this? please assign it to me

**Comment by salted0dreams** [comment]
Can i work on this?

**Comment by Balaguru4580** [comment]
@salted0dreams  Sure!
